INSERT INTO `product` (product_name, quantity, value, description) VALUES ('computador','10', '1000000', 'computador HP');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('mouse inalambrico','0', '40000', 'mouse genius inalambrico');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('teclado usb','15', '30000', 'teclado usb lenovo');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('router','20', '500000', 'router cisco');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('impresora laser','8', '3000000', 'impresora laser lexmark');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('cable utp','40', '10000', 'cable rj45 utp');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('monitor plano','20', '200000', 'monitor plano marca lenovo');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('adaptador de corriente','30', '130000', 'adaptador de corriente pc portatil');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('memoria ram','15', '80000', 'memoria ram 4gb');
INSERT INTO `product` (product_name, quantity, value, description) VALUES ('disco duro','20', '200000', 'disco duro sdd marca seagate');